apiVersion: core/v1
kind: Pod
metadata:
  name: jupyterhub-slurm
spec:
  containers:
    - name: jupyterhub
      image: localhost/brics_jupyterhub:latest
      ports:
        - containerPort: 8000
          hostIP: 127.0.0.1
          hostPort: 8000
          protocol: TCP
      volumeMounts:
        # JupyterHub configuration
        - name: jupyterhub_root_vol
          mountPath: /etc/jupyterhub
          readOnly: true
          subPath: /etc/jupyterhub

        # JupyterHub logs
        - name: jupyterhub_root_vol
          mountPath: /srv/jupyterhub
          readOnly: false
          subPath: /srv/jupyterhub

        # JupyterHub server data
        - name: jupyterhub_root_vol
          mountPath: /var/log/jupyterhub
          readOnly: false
          subPath: /var/log/jupyterhub

    - name: slurm
      image: localhost/brics_slurm:latest

  volumes:
    - name: jupyterhub_root_vol
      persistentVolumeClaim:
        claimName: jupyterhub_root
        readOnly: false


 