apiVersion: core/v1
kind: Pod
metadata:
  name: jupyterhub-slurm
spec:
  containers:
    - name: jupyterhub
      image: localhost/brics_jupyterhub:latest
      ports:
        - containerPort: 8000
          hostIP: 127.0.0.1
          hostPort: 8000
          protocol: TCP

    - name: slurm
      image: localhost/brics_slurm:latest
