apiVersion: core/v1
kind: Pod
metadata:
  name: jupyterhub-slurm
spec:
  containers:
    - name: jupyterhub
      image: localhost/brics_jupyterhub:latest
      ports:
        - containerPort: 8000
          hostIP: 127.0.0.1
          hostPort: 8000
          protocol: TCP
      volumeMounts:
        # JupyterHub configuration
        - name: jupyterhub_root_vol
          mountPath: /etc/jupyterhub
          readOnly: true
          subPath: /etc/jupyterhub

        # JupyterHub server data
        - name: jupyterhub_root_vol
          mountPath: /srv/jupyterhub
          readOnly: false
          subPath: /srv/jupyterhub

        # JupyterHub logs
        - name: jupyterhub_root_vol
          mountPath: /var/log/jupyterhub
          readOnly: false
          subPath: /var/log/jupyterhub

        # SSH key from Secret
        - name: ssh_key_vol
          mountPath: /srv/jupyterhub/ssh
          readOnly: true

    - name: slurm
      image: localhost/brics_slurm:latest

      volumeMounts:
        # slurmctld log file
        - name: slurm_root_vol
          mountPath: /var/log/slurmctld.log
          readOnly: false
          subPath: /var/log/slurmctld.log

        # slurmd log file
        - name: slurm_root_vol
          mountPath: /var/log/slurmd.log
          readOnly: false
          subPath: /var/log/slurmd.log

        # slurmctld spool directory
        - name: slurm_root_vol
          mountPath: /var/spool/slurmctld
          readOnly: false
          subPath: /var/spool/slurmctld

        # slurmd spool directory
        - name: slurm_root_vol
          mountPath: /var/spool/slurmd
          readOnly: false
          subPath: /var/spool/slurmd

  volumes:
    - name: jupyterhub_root_vol
      persistentVolumeClaim:
        claimName: jupyterhub_root
        readOnly: false

    - name: slurm_root_vol
      persistentVolumeClaim:
        claimName: slurm_root
        readOnly: false

    - name: ssh_key_vol
      secret:
        secretName: jupyterhub-slurm-ssh-key



 