FROM quay.io/jupyterhub/jupyterhub:latest

# Install packages from distribution repos: SSH client
RUN <<EOF
apt-get update && apt-get install --assume-yes --no-install-recommends openssh-client
apt-get clean
rm -rf /var/lib/apt/lists/*
EOF

# Install packages from PyPI: batchspawner
RUN python3 -m pip install --no-cache-dir --root-user-action=ignore batchspawner

# Set useful environment variables
ENV JUPYTERHUB_CONFIG_DIR="/etc/jupyterhub" \
JUPYTERHUB_SRV_DIR="/srv/jupyterhub" \
JUPYTERHUB_LOG_DIR="/var/log/jupyterhub" \
JUPYTERHUB_LAUNCHER="/usr/local/bin/start-jupyterhub"

# Create JupyterHub config, srv, and log directories
# These should usually be bind-mounted to locations on the host when running the container
RUN mkdir --verbose --parents "${JUPYTERHUB_CONFIG_DIR}" "${JUPYTERHUB_SRV_DIR}" "${JUPYTERHUB_LOG_DIR}"

# Create JupyterHub launcher script: Owned by root, world-readable and executable
# NOTE: Here doc delimiter is quoted ("EOF") to prevent parameter expansion when writing file
RUN cat > "${JUPYTERHUB_LAUNCHER}" <<"EOF" && chmod --verbose u=rwx,g=rx,o=rx "${JUPYTERHUB_LAUNCHER}"
#!/bin/bash
cd "${JUPYTERHUB_SRV_DIR}"
JUPYTERHUB_CONFIG_FILE="${JUPYTERHUB_CONFIG_DIR}/jupyterhub_config.py"
JUPYTERHUB_LOG_FILE="${JUPYTERHUB_LOG_DIR}/jupyterhub_log_$(date +%Y%m%d-%H%M%S).log"

set -x
exec /usr/local/bin/jupyterhub -f "${JUPYTERHUB_CONFIG_FILE}" "$@" 2>&1 | tee "${JUPYTERHUB_LOG_FILE}"
EOF

# Generate default configuration file and place in JupyterHub configuration directory
RUN <<EOF
cd "${JUPYTERHUB_CONFIG_DIR}"
jupyterhub --generate-config
EOF

CMD ["start-jupyterhub", "--debug"]